### ISSUE TITLE
Man, you are awesome!

### ISSUE THREAD

**Issue by Moris-Shalon** [mxs42/mutegram#1]
Man, you are awesome! Your tool really works. I am surprised a lot. Let me show my respect to you. Seriosly, I have thought a lot about this problem before, and now I have found your tool and I can't believe it actually works. Thank you very much!
Tested on Telegram Desktop version 1.3.14 with Windows 10 notification's enabled in app.

**Comment by mxs42** [comment]
I'm glad it's useful for you :)
