### ISSUE TITLE
Not working in Telegram Desktop 1.5.9

### ISSUE THREAD

**Issue by Logerfo** [mxs42/mutegram#3]
> [ERROR] Can't patch Telegram executable. Maybe you've already patched it or this tool doesn't support current Telegram version.

**Comment by LordZiru** [comment]
not working on telegram 1.5.11

[ERROR] Can't patch Telegram executable. Maybe you've already patched it or this tool doesn't support current Telegram version.

**Comment by Logerfo** [comment]
This is probably happening because of one of those refactorings: https://github.com/telegramdesktop/tdesktop/commit/4111da1dd0926d657e5205744111b2c6fec7b61c and https://github.com/telegramdesktop/tdesktop/commit/a70e72f75d01b7865d5a22b393f03e80ee6b4710

**Comment by Perlence** [comment]
This is the part of the function that has changed:

![image](https://user-images.githubusercontent.com/1044300/52167244-4b2ea000-2729-11e9-8780-8ff52e31e2b7.png)

I suggest this patch:
```diff
-const auto target = SignatureScan(map, size, "74 ? 8B BF ? ? ? ? 85 FF 74 ? 8B B7 ? ? ? ? FF 15 ? ? ? ?");
+const auto target = SignatureScan(map, size, "74 ? 8B 78 ? 85 FF 74 ? 8B B7 ? ? ? ? FF 15 ? ? ? ?");
```

**Comment by Moris-Shalon** [comment]
can someone compile mutegram with these changes? I don't understand, how to do it, using mingw g++ compiler

**Comment by alexlyzhov** [comment]
Not working for me either

**Comment by mxs42** [comment]
Eh, I didn't close Telegram for almost 2 weeks so I missed the update.
I'm looking into it right now...

**Comment by mxs42** [comment]
Fixed, thanks to @Perlence for providing correct new signature.
I uploaded new binary in Releases section.
