### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by Hypfer** [mxs42/mutegram#7]
While this certainly isn't strictly related to the code as it is, I was wondering how one can proceed to adapt this to other applications.
I am loosing my mind over the constant and permanent taskbar flashing of Microsoft teams.

Any pointers?

Edit2:
```
file Teams.exe
Teams.exe: PE32+ executable (GUI) x86-64, for MS Windows`
```

Looking at `EasyHook32.dll` I'd assume that that is the issue?

**Comment by Kadeluxe** [comment]
Sorry for a late reply, I changed my primary Github account and didn't bother to check this repo.
Yes, it is indeed possible to adapt this universally to any Windows app that uses FlashWindowEx.
Actually I think it should already work for any app that imports **winmm.dll**. The thing is that I used dll proxying to automatically inject code but if MS Teams doesn't load winmm.dll or loads it in a custom way then this proxy won't load.

Let me know if this is still relevant, I can look into it to give further tips/info.

**Comment by Hypfer** [comment]
I've actually managed to achieve the desired result:

https://github.com/Hypfer/SilenTeams

Thanks though :)

**Comment by Kadeluxe** [comment]
Looks good! I didn't even know about this [NoFlashWindow](https://github.com/mrexodia/NoFlashWindow) repo you linked, it could be very helpful when Telegram finally bothered me enough back in the day haha. 
I wish Windows had that flashing control per-app already.

Also related project I recently used, generates proxy DLL automatically, maybe it will be useful for future strangers!
https://github.com/nitrog0d/DLLProxyGenerator
